from decouple import config


DJANGO_DEBUG = config("DJANGO_DEBUG", default=False, cast=bool)
TASK_VERSION = config("TASK_VERSION", default="3")


USER_NAME_MAX_LENGTH = 124
USER_SURNAME_MAX_LENGTH = 124
USER_PHONE_MAX_LENGTH = 12
USER_ABOUT_MAX_LENGTH = 256

PAGINATION_PAGE_SIZE = 12

PHONE_NATIONAL_PREFIX = "8"
PHONE_COUNTRY_CODE_PREFIX = "+7"
PHONE_DIGITS_COUNT = 10
PHONE_RANDOM_DIGIT_LIMIT = 10

PHONE_REGEX = r"^(8|\+7)\d{10}$"
GITHUB_URL_REGEX = (
    r"^https?:\/\/(www\.)?github\.com\/[\w\-\.]+(\/[\w\-\.]+)?\/?$"
)


PROJECT_NAME_MAX_LENGTH = 200
PROJECT_STATUS_MAX_LENGTH = 6

PROJECT_STATUS_OPEN = "open"
PROJECT_STATUS_CLOSED = "closed"

PROJECT_STATUS_CHOICES = [
    (PROJECT_STATUS_OPEN, "Open"),
    (PROJECT_STATUS_CLOSED, "Closed"),
]


SKILL_NAME_MAX_LENGTH = 124
SKILL_AUTOCOMPLETE_LIMIT = 10


AVATAR_IMAGE_SIZE = 256
AVATAR_TEXT_FONT_SIZE = 128

AVATAR_TEXT_COLOR_LIGHT = "#FFFFFF"
AVATAR_TEXT_COLOR_DARK = "#111111"

AVATAR_BG_COLOR_SAGE = "#A3B18A"
AVATAR_BG_COLOR_BEIGE = "#DDBEA9"
AVATAR_BG_COLOR_ASH = "#B7B7A4"
AVATAR_BG_COLOR_OLIVE = "#6B705C"
AVATAR_BG_COLOR_SAND = "#CB997E"
AVATAR_BG_COLOR_STONE = "#A5A58D"

AVATAR_BG_COLORS = [
    AVATAR_BG_COLOR_SAGE,
    AVATAR_BG_COLOR_BEIGE,
    AVATAR_BG_COLOR_ASH,
    AVATAR_BG_COLOR_OLIVE,
    AVATAR_BG_COLOR_SAND,
    AVATAR_BG_COLOR_STONE,
]

BRIGHTNESS_RED_WEIGHT = 299
BRIGHTNESS_GREEN_WEIGHT = 587
BRIGHTNESS_BLUE_WEIGHT = 114
BRIGHTNESS_DIVISOR = 1000
BRIGHTNESS_THRESHOLD = 140
HEX_RED_START = 0
HEX_RED_END = 2
HEX_GREEN_START = 2
HEX_GREEN_END = 4
HEX_BLUE_START = 4
HEX_BLUE_END = 6
HEX_BASE = 16


ABOUT_TEXTAREA_ROWS = 4


DEFAULT_ORDERING_DESC = "-created_at"
DEFAULT_ORDERING_ASC = "id"


INVALID_GITHUB_URL_MESSAGE = "Invalid GitHub URL"
INVALID_PHONE_MESSAGE = "Invalid phone format"
PHONE_REQUIRED_MESSAGE = "Phone is required"
PHONE_EXISTS_MESSAGE = "Phone already exists"
INVALID_GITHUB_URL_MESSAGE = "Invalid GitHub URL"
PASSWORDS_DONT_MATCH_MESSAGE = "Passwords don't match"
INVALID_LOGIN_CREDENTIALS_MESSAGE = "Invalid email or password"
PROJECT_CLOSED_MESSAGE = "Project is closed"
PROJECT_NOT_FOUND_MESSAGE = "Project not found"
SKILL_NOT_FOUND_MESSAGE = "Skill not found"
USER_NOT_FOUND_MESSAGE = "User not found"
AUTHENTICATION_REQUIRED_MESSAGE = "Authentication required"
FORBIDDEN_MESSAGE = "Forbidden"
SKILL_DATA_REQUIRED_MESSAGE = "Skill data is required"
SKILL_NOT_ATTACHED_MESSAGE = "Skill is not attached to project"
PROJECT_ALREADY_CLOSED_MESSAGE = "Project is already closed"
