# team_finder/constants.py
from decouple import config


# AUTH / ENV SETTINGS

DJANGO_DEBUG = config("DJANGO_DEBUG", default=False, cast=bool)
TASK_VERSION = config("TASK_VERSION", default="1")


# USER VALIDATION

USER_NAME_MAX_LENGTH = 124
USER_SURNAME_MAX_LENGTH = 124
USER_PHONE_MAX_LENGTH = 12
USER_ABOUT_MAX_LENGTH = 256

PAGINATION_PAGE_SIZE = 12

PHONE_NATIONAL_PREFIX = "8"
PHONE_COUNTRY_CODE_PREFIX = "+7"
PHONE_DIGITS_COUNT = 10

PHONE_REGEX = r"^(8|\+7)\d{10}$"
GITHUB_URL_REGEX = r"^https?:\/\/(www\.)?github\.com\/[\w\-\.]+(\/[\w\-\.]+)?\/?$"


# PROJECT RULES

PROJECT_NAME_MAX_LENGTH = 200
PROJECT_STATUS_MAX_LENGTH = 6

PROJECT_STATUS_OPEN = "open"
PROJECT_STATUS_CLOSED = "closed"

PROJECT_STATUS_CHOICES = [
    (PROJECT_STATUS_OPEN, "Open"),
    (PROJECT_STATUS_CLOSED, "Closed"),
]


# SKILL RULES

SKILL_NAME_MAX_LENGTH = 124
SKILL_AUTOCOMPLETE_LIMIT = 10


# AVATAR

AVATAR_IMAGE_SIZE = 256
AVATAR_TEXT_FONT_SIZE = 128

AVATAR_TEXT_COLOR_LIGHT = "#FFFFFF"
AVATAR_TEXT_COLOR_DARK = "#111111"

AVATAR_BG_COLOR_SAGE = "#A3B18A"
AVATAR_BG_COLOR_BEIGE = "#DDBEA9"
AVATAR_BG_COLOR_ASH = "#B7B7A4"
AVATAR_BG_COLOR_OLIVE = "#6B705C"
AVATAR_BG_COLOR_SAND = "#CB997E"
AVATAR_BG_COLOR_STONE = "#A5A58D"

AVATAR_BG_COLORS = [
    AVATAR_BG_COLOR_SAGE,
    AVATAR_BG_COLOR_BEIGE,
    AVATAR_BG_COLOR_ASH,
    AVATAR_BG_COLOR_OLIVE,
    AVATAR_BG_COLOR_SAND,
    AVATAR_BG_COLOR_STONE,
]


# QUERY / PAGINATION

DEFAULT_ORDERING_DESC = "-created_at"
DEFAULT_ORDERING_ASC = "id"
